### PR TITLE
Fixed CordovaPlugin-Error

### PR DESCRIPTION
**Pull request by khayalan-mathew**
Fixed the error, that Cordova-Plugins dont load :)

### CODE REVIEW

**Comment by unimonkiez** [comment]
Looks good man!
Though I would like it not to error the desktop build, as the resource is only injected on a cordova application.

**Comment by khayalan-mathew** [comment]
I will look into a method to fix that ^^ Maybe we can add a option in webpack to use a different .ejs file if the npm run build:cordova (or the Cordova Environment) is selected. But atm i dont know how to do it, but i will definetly check it out

**Comment by khayalan-mathew** [comment]
So i got the new version and i'm going to make a new pullrequest tomorrow ^^

**Comment by khayalan-mathew** [comment]
So added now NON-Cordova Support

**Comment by unimonkiez** [comment]
You can use the `__CORDOVA__` boolean directly in the ejs file, no need to do seperate files

**Comment by khayalan-mathew** [comment]
@unimonkiez Done this

**Comment by unimonkiez** [comment]
Thanks! 😄

**Pull request merged**
